### ISSUE TITLE
Item deduplication needed on output

### ISSUE THREAD

**Issue by remyrd** [mattydebie/bitwarden-rofi#19]
Simply put: `name` is not a unique id in bitwarden, and shouldn't be used to retrieve items.
Eg. https://github.com/mattydebie/bitwarden-rofi/blob/master/bwmenu#L97
`id` should be used instead.
Problem is I'm not sure rofi can hide part of the input it's been given...

**Comment by Mange** [comment]
>  Problem is I'm not sure rofi can hide part of the input it's been given...

It can not. I've tried this before.

`fzf` can do it `--nth` and `--with-nth` options:

```
    -n, --nth=N[,..]      Comma-separated list of field index expressions
                          for limiting search scope. Each can be a non-zero
                          integer or a range expression ([BEGIN]..[END]).
    --with-nth=N[,..]     Transform the presentation of each line using
                          field index expressions
```

I wish rofi had something similar to this. :(

**Comment by remyrd** [comment]
Just a thought, I believe there are other ways out of this...
- I commented on another issue https://github.com/mattydebie/bitwarden-rofi/issues/12#issuecomment-490561609 and well, assuming the user can "visually" deduplicate the entries since there is more metadata on each item and some templating maps the format to the fields in `ITEMS`, one could use additional `select()` statements (functions?) in `jq` to return the one good entry. Still, the user can't expect to get a different entry when selecting the **second** identical option
- Deduplication could be offloaded to another rofi instance, offering initially a list of entries uniquely identified by whatever string the user configures.

**Comment by Mange** [comment]
When I did [Mange/rofi-lpass](https://github.com/Mange/rofi-lpass) (LastPass in Rofi) I added the ID to each entry like this:

> Some Site [`<ID>`]

> Copy password [`<ID>`]
> Copy username [`<ID>`]
> …

Then I could extract the ID on each line.

We could also use the built-in support for [Pango markup](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html) (with the `-markup-rows` option to Rofi) to make the ID markers really small so it doesn't stick out as much.

**Comment by mattydebie** [comment]
Maybe the most generic way to handle this is to indeed use a second rofi to finetune the selection.
When you use bwmenu for searching folders this actually already happens. This could be really easy to add imo.
