### ISSUE TITLE
Cannot load user/pass list.

### ISSUE THREAD

**Issue by Phate6660** [mattydebie/bitwarden-rofi#24]
I'm getting the error "could not load items". I've made sure to install all the dependencies, and I have successfully logged into bitwarden-cli. I've checked to make sure that both bw and rofi work, and they both do.

Is there anything else that I'm supposed to do that I missed?

I'm currently running Gentoo if that helps.

**Comment by mattydebie** [comment]
The error you're describing can only happen in this peace of code:
```bash
load_items() {
  if ! ITEMS=$(bw list items --session "$BW_HASH" 2>/dev/null); then
    exit_error $? "Could not load items"
  fi
}
```
I would suggest running the `bw list items --session "$BW_HASH"` in your terminal and verify what the return value is.
The $BW_HASH can be found by running `keyctl pipe $(keyctl request user bw_session)` or by manually unlocking bitwarden using _bitwarden-cli_

**Comment by Phate6660** [comment]
I apparently don't have keyctl installed, however I can successfully get a list of my usernames and passwords by manually unlocking bitwarden and using the list subcommand.

**Comment by mattydebie** [comment]
Hmm, I though keyctl was by default installed on all systems. The fact you're running gentoo might have something to do with it :stuck_out_tongue: 
At the moment I don't see a way to run this script without keyctl. 
Are you able to install it? [you can find it here](https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/tree/)

**Comment by Phate6660** [comment]
Just installed keyctl. Everything works perfectly now. Thank you for the help.

> The fact you're running gentoo

Iirc, Gentoo uses a modified kernel (it was significantly slimmed down from what I can remember) by default. Judging by the link you sent, it's probably included with the vanilla kernel or something? So perhaps it was removed from Gentoo's kernel due to being un-needed or something.

**Comment by mattydebie** [comment]
Awesome! Glad to hear it :grin: 

> perhaps it was removed from Gentoo's kernel due to being un-needed or something.  

That's definitely possible, but that's a mistake from Gentoo if you ask me if they don't provide an alternative.

Anyways, glad this got resolved :grinning:
