### ISSUE TITLE
Use ydotool when available for wayland users

### ISSUE THREAD

**Issue by touste** [mattydebie/bitwarden-rofi#25]
[ydotool](https://github.com/ReimuNotMoe/ydotool) is a replacement for xdotool that works in Wayland. If it is detected, it could replace xdotool to type username and password for Wayland users.

Note that it requires root permissions to run, so it should be called with sudo and the user should allow this in visudo (ex: `user ALL=(ALL) NOPASSWD: /usr/bin/ydotool`).

Thanks!

**Comment by mattydebie** [comment]
I think I came across it too one time in the past. Having to insert a line into visudo is not really an easy setup anymore. You should be able to just download the bash script and run it. 
Anyways, as I use X, I can not test this. PR's are always welcome! :smile:

**Comment by touste** [comment]
Thanks for the feedback, I agree that it is not an ideal solution but at
the moment it's the only one available for Wayland users to my knowledge.
I'll try to update the code and make a PR.

**Comment by mattydebie** [comment]
True, it's better to provide something rather than nothing :grin: 
Thanks for your time!

**Comment by lambdadade** [comment]
ydotool works for me with user permissions without sudo. So I removed sudo from the script.
I am starting ydotoold via "systemd --user"
