### ISSUE TITLE
can not access keyctl, permission denied

### ISSUE THREAD

**Issue by jrvgr** [mattydebie/bitwarden-rofi#27]
when i try to open my vault i get a error from keyctl and i dont know what to do
![image](https://user-images.githubusercontent.com/30769091/62436890-5ba7ed80-b741-11e9-9a3b-5802b02342a7.png)

**Comment by jrvgr** [comment]
in sudo it give the same errors

**Comment by eyadsibai** [comment]
getting same error

**Comment by collinsleewyatt** [comment]
What distro are you running?

**Comment by d3vv3** [comment]
Hi! I have the same issue.
I am on Debian 10. Once I type my Master Password, it gives me a `Could not load items`, followed by 
```
keyctl_set_timeout: Permission denied
keyctl_read_alloc: Permission denied
```
on the terminal (I started bwmenu on the terminal for debugging).

Lets see if we can fix this!

**Comment by collinsleewyatt** [comment]
I'll boot up a Debian VM and see what's going on.

**Comment by collinsleewyatt** [comment]
I'm able to get the problem to replicate on Debian 10.1 on Mate (pretty sure it's xorg) with xclip,  xsel, and xdotool installed. I also tried logging in as root and seeing if that resolved anything, which didn't work.

Might be an issue with systemd? Just speculating. I'll try on arch.

**Comment by d3vv3** [comment]
I will check tomorrow and update you, any news with arch?

**Comment by d3vv3** [comment]
Any news with arch or ubuntu (or any other systemd)? I couldn't achieve anything on my side...

**Comment by pltanton** [comment]
Same issue with NixOS

**Comment by pltanton** [comment]
```
➜  bitwarden-rofi git:(master) ✗ systemctl show user-runtime-dir@1000.service | grep KeyringMode                                                                         
KeyringMode=private
➜  bitwarden-rofi git:(master) ✗ systemctl show user@500.service | grep KeyringMode                                                                                      
KeyringMode=inherit
```

I guess the problem in 'KeyringMode=private`

**Comment by pltanton** [comment]
@virivongithub Why you closed that? Do you find a solution?

**Comment by d3vv3** [comment]
Please update the issue, how did you solve it (if you did)?

**Comment by Dzordzu** [comment]
Same here:

## System info

* Arch
* bwmenu 0.4
* bw 1.8.0

## When it happens?
1. After logout
2. Random moments (most frequent)
3. When using root (I consider it as a good behavior)

**Comment by Dzordzu** [comment]
Please reopen this issue
