### ISSUE TITLE
could not unlock vault error

### ISSUE THREAD

**Issue by eyadsibai** [mattydebie/bitwarden-rofi#29]
getting could not unlock vault error. 

I installed it using the AUR.

**Comment by mattydebie** [comment]
Can you provide more of the steps you took leading to this error?

**Comment by eyadsibai** [comment]
unfortunately, that's the only step I did. I installed it on Manjaro distro. Then I tried to login. whenever I write my master password . I get this error

**Comment by mattydebie** [comment]
Don't forget to use bw-cli to login first.

bw login your@email.com

**Comment by eyadsibai** [comment]
Thanks that worked!
