### ISSUE TITLE
keyctl: Permission Denied

### ISSUE THREAD

**Issue by pltanton** [mattydebie/bitwarden-rofi#34]
While trying to call `bwmenu` I got:

```
keyctl_set_timeout: Permission denied
keyctl_read_alloc: Permission denied
```

Previous thread: #28

**Comment by kylesferrazza** [comment]
I've got the same issue running systemd 243.

Reading a key from `@u` seems to fail, even as root:
```bash
$ keyctl padd user bw_session @u
test
988710383

$ keyctl read 988710383
keyctl_read_alloc: Permission denied
```
https://github.com/systemd/systemd/issues/5522 might be useful?

**Comment by d3vv3** [comment]
I am here as well, there is a closed issue regarding this, but it isn't solved (?)

**Comment by pltanton** [comment]
Can we implement a fork or an option to store secrets with another secret storage provider like gnome-keyring org kwallet?

**Comment by arekceg** [comment]
Same issue here:
`keyctl_set_timeout: Permission denied`
`keyctl_read_alloc: Permission denied`

Works well on my laptop with Manjaro but will not work on my PC running Mint

**Comment by kylesferrazza** [comment]
Anyone solve this / have a workaround?

**Comment by trevorriles** [comment]
I solved this by installing `keyutils` and running `keyctl link @u @s` after logging into the cli. That linked the secret in my user key ring to my session keyring which bwmenu can access.

**Comment by symphorien** [comment]
I confirm `keyctl link @u @s` solves the problem

**Comment by tashrifbillah** [comment]
> I confirm `keyctl link @u @s` solves the problem

Does not work for me on a CentOS 7 Linux. I still get permission denied on `keyctl timeout <keyring> <timeout>`

**Comment by TSoli** [comment]
> I confirm `keyctl link @u @s` solves the problem

Yep me too (on Linux Mint). Just in case anyone is not sure how to include this in the program automatically just open up `bwmenu` with vim or something and change the `ask_password()` function like so

```bash
ask_password() {
  rm $CACHE_FILE
  mpw=$(printf '' | rofi -dmenu -p "Master Password" -password -l 0 ${ROFI_OPTIONS[@]}) || exit $?
  if ! out="$(bw --raw --nointeraction unlock "$mpw" 2>&1)"; then
    exit_error 1 "Could not unlock vault: $out"
  fi
  keyctl link @u @s  # Add this line
  echo "$out"
}
```
