### ISSUE TITLE
allow using rofi themes

### ISSUE THREAD

**Issue by autoferrit** [mattydebie/bitwarden-rofi#45]
As the name suggests. would it be possible to add a theme flag that would then be passed to rofi to use an existing theme?

**Comment by mirkobrombin** [comment]
```
Usage:
  bwmenu [options] -- [rofi options]
```

So I think just need to append as rofi options.

**Comment by mattydebie** [comment]
That's correct! You can append any rofi options 😁

**Comment by autoferrit** [comment]
great thanks.
