### ISSUE TITLE
Workaround for error "Could not load items"

### ISSUE THREAD

**Issue by winiciuscota** [mattydebie/bitwarden-rofi#57]
I get this error a few times a week, when this happens calling bitwarden-rofi will only show a small dialog with this message("Could not load items"). Is there any way to recover from this error(maybe restarting some service)? right now the only solution I found is to reboot.

**Comment by Prior99** [comment]
I just installed this and have the same issue.

**Comment by nylocx** [comment]
Hi, I get the same error with a fresh install and also see this errors https://github.com/mattydebie/bitwarden-rofi/issues/27.
I figured that https://github.com/mattydebie/bitwarden-rofi/issues/34#issuecomment-641506873 also solves this issue.

**Comment by PiQuer** [comment]
For me ``keyctl link @u @s`` does not help. I can reproduce the issue as follows:

1. Call bwmenu and enter the master password.
2. Call 'bw' on the command line, it asks for the master password again.
3. Now bwmenu always shows "Could not load items".

I don't know if it is relevant or not, but I have two-factor authentication enabled.

**Comment by PiQuer** [comment]
``keyctl purge user bw_session`` helps in my situation.

**Comment by winiciuscota** [comment]
```keyctl purge user bw_session``` Does exactly what I was looking for. Thanks.
