### ISSUE TITLE
Releasing to the AUR (Arch User Repository)

### ISSUE THREAD

**Issue by Mange** [mattydebie/bitwarden-rofi#6]
I intend to publish this project on the AUR (unless you want to do it yourself).

Before I do that, I'd prefer if you could tag a release so I can use that release tarball as the source for the package version (and to keep them in sync). Would you mind tagging a release that I can base the package on?

I could also go for a `bitwarden-rofi-git` package that always takes latest `master`, but I prefer stable fixed-in-time versions for my package managers.

I can send you a PR afterwards with some updated instructions in the README about this.

**Comment by mattydebie** [comment]
I would love to see it published to the AUR! 
I would do it myself, but haven't really looked into the 'how' part, so you can go ahead and do it.
I'll merge the PR and tag a release

**Comment by mattydebie** [comment]
There you go, [0.1](https://github.com/mattydebie/bitwarden-rofi/releases/tag/0.1) is tagged!

**Comment by Mange** [comment]
Thank you. I'll get back to you when I have time to make the package.
Now I need to get back to work again! :laughing:

**Comment by mattydebie** [comment]
Same here, good luck 😁

**Comment by fnune** [comment]
You guys rock! Thanks!
