### ISSUE TITLE
Changing keybinding

### ISSUE THREAD

**Issue by yreew** [mattydebie/bitwarden-rofi#74]
How do I change the keybindings? In most of the WMs, alt+(1-9) keys are used to change workspace.

Thank you in advance.

**Comment by BiliBraker** [comment]
I think you can just change the [following lines](https://github.com/mattydebie/bitwarden-rofi/blob/62c95afd5634234bac75855dc705d4da5f4fab69/bwmenu#L27-L35) in the `bwmenu` script.

**Comment by mattydebie** [comment]
@yreew I myself use i3wm, so alt+[0-9] is also used for switching workspaces, but the shortcuts still work because rofi takes over at the moment. However, you can now define the shortcuts yourself because #75 is merged.
