### ISSUE TITLE
Could not load items error

### ISSUE THREAD

**Issue by ReinerSanders** [mattydebie/bitwarden-rofi#87]
Hi,

I am using the script on Linux (EndeavourOS with i3) and it stopped working a few days ago.

Now when I run it, and after enter the password to unlock my vault, the "could not load items" error appears.

Any idea on how to solve this, please?

Thanks in advance.

**Comment by vargn** [comment]
I am seeing the same error. It appeared after updating my system to Manjaro 24.0 with i3.

**Comment by ReinerSanders** [comment]
This is strange. I also have i3 here. :(

**Comment by vargn** [comment]
Could it be related to the fix mentioned in issue [#83](https://github.com/mattydebie/bitwarden-rofi/issues/83) and [#84](https://github.com/mattydebie/bitwarden-rofi/issues/84)?

**Comment by vargn** [comment]
This seems to be the issue:
```
rm: cannot remove '/tmp/bwmenu/logins.gpg': No such file or directory
```

However, I tried creating this file, and it gets deleted. But loading items still fails.
Additionally, there's this:
```
$ bw list items --session 'key'
mac failed
```

**EDIT:** Seems as if the latest version is [v2024.4.1](https://github.com/bitwarden/clients/releases/), but the package in Arch/Manjaro repo is currently still at [v2024.4.0](https://archlinux.org/packages/extra/x86_64/bitwarden-cli/).

**Comment by ReinerSanders** [comment]
I also tried that without success, unfortunately.

So it seems we will have to wait for an update?

**Comment by vargn** [comment]
Package has now been updated to 2024.4.1 on the Arch repo, but not on the Manjaro repo.

**Comment by ReinerSanders** [comment]
Yes. It solved the problem here (EndeavourOS).

**Comment by vargn** [comment]
Confirmed working with package version 2024.4.1

**Comment by mattydebie** [comment]
Alright that's good news, had a pretty heavy week so far so wasn't able to look into it 😅
